// File generated by FlutterFire CLI.
// This file is used to configure Firebase for your Flutter application.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Actual Web configuration
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbL2N_qtyI8lcg7GWK0X-l8hAg2gSWhCs',
    appId: '1:918561985276:web:e5e48b4382065473ba3d79',
    messagingSenderId: '918561985276',
    projectId: 'farminggodsway-a31d4',
    authDomain: 'farminggodsway-a31d4.firebaseapp.com',
    storageBucket: 'farminggodsway-a31d4.firebasestorage.app',
    measurementId: 'G-06EZME3JZP',
  );

  // Android configuration using the same project
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbL2N_qtyI8lcg7GWK0X-l8hAg2gSWhCs',
    appId: '1:918561985276:android:e5e48b4382065473ba3d79',
    messagingSenderId: '918561985276',
    projectId: 'farminggodsway-a31d4',
    storageBucket: 'farminggodsway-a31d4.firebasestorage.app',
  );

  // iOS configuration using the same project
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbL2N_qtyI8lcg7GWK0X-l8hAg2gSWhCs',
    appId: '1:918561985276:ios:e5e48b4382065473ba3d79',
    messagingSenderId: '918561985276',
    projectId: 'farminggodsway-a31d4',
    storageBucket: 'farminggodsway-a31d4.firebasestorage.app',
    iosBundleId: 'com.example.farming_gods_way',
  );
}
